### ISSUE TITLE
the reconstruction get worse when use depth

### ISSUE THREAD

**Issue by yueyunqingwu** [Jianxff/droid_metric#1]
hi, thank you for your great work. I notice that the reconstruction get worse when use depth in your readme.md, I get the same result, how to impove it? Thanks!

**Comment by Jianxff** [comment]
thanks for your feedback.
I'm not so clear about your question, did you mean an inaccurate trajectory or a low quality of the visual scene?

If it is the latter, you can try to press key 'S' on your keyboard to increase filter to get denser pointcloud （press 'A' to decrease）. Notice that denser pointcloud will take up more video memory. Change params on file '[renderoption.json](https://github.com/Jianxff/droid_metric/blob/main/misc/renderoption.json)' may also improve the visualization quality.

If it is about the trajectory, it may caused by inaccurate depth estimation or DROID-SLAM system. I'm sorry that currently I donot have good ideas to improve it.

**Comment by yueyunqingwu** [comment]
Thank you for your reply. I mean a low quality of the visual scene under the same visualization settings.
![image](https://github.com/Jianxff/droid_metric/assets/41660286/929659f5-4abc-403d-ac9c-6e2b2acb179e)
without_depth.jpg
![image](https://github.com/Jianxff/droid_metric/assets/41660286/540cfbf5-130f-44a8-91ba-1d01b78b69be)
with_depth.jpg

**Comment by qiuhaining** [comment]
not find submodule in this repo, what is the submodule commitid?

**Comment by Jianxff** [comment]
@qiuhaining sorry for that, it may has been fixed now.

**Comment by Jianxff** [comment]
@yueyunqingwu sorry I don't have much ideas for it. You can press 'S' to increase the depth filter on visualize, if it doesn't work I think it may caused by a wrong depth estimation.

**Comment by yueyunqingwu** [comment]
@Jianxff Thank you for your kindly reply!
