### ISSUE TITLE
Installation and usage is unclear:

### ISSUE THREAD

**Issue by Asylbeck** [Jianxff/droid_metric#8]
when installing - this command installs torch version 11.7
`conda install pytorch==2.0.0 torchvision==0.15.0 pytorch-cuda=11.7 -c pytorch -c nvidia`
afterwards the install script from metric module requires cuda 12.1 and according torch version.
In the end when running:
`python depth.py --rgb /home/user/git/droid_metric/data/advio-15/iphone/frames --out /home/user/git/droid_metric/out --intr /home/user/git/droid_metric/data/advio-15/iphone/intrinsics.txt`
I get this error:
`Loading model v2-g from /home/bek/git/droid_metric/weights/metric_depth_vit_giant2_800k.pth
/home/bek/.conda/envs/droid_metric/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/bek/.conda/envs/droid_metric/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
NO pretrained imagenet ckpt available! Check your path!
Traceback (most recent call last):
  File "/home/bek/git/droid_metric/depth.py", line 32, in <module>
    image_dir = Path(args.images).resolve(`
    
 Unclear whether it's the installation error, incorrect run command or missing parameter.
 Same goes for this command:
 `python run.py --rgb $/path/to/rgb/dir --depth $/path/to/depth/dir --intr $/path/to/intrinsic/file --viz`
 where is depth folder supposed to be found, does it need to be generated first?

**Comment by Jianxff** [comment]
Hi，
Before running `run.py`, you should run `depth.py` for depth estimation first. I don't make it simultaneous with SLAM thread.

For the warning, I'm sorry I forgot update the code after argument change.  [This line](https://github.com/Jianxff/droid_metric/blob/7f1bb631043db8fa8b4bcc8d3430a88d75cc6304/depth.py#L32) should be writen as `image_dir = Path(args.rgb).resolve()`.

For installation, the error may comes from the auto-update of torch when installing `mmcv`, `timm` and `xformers`. I'm working on it now. Btw, CUDA 12.1 may also work for this repo, you can try install pytorch and torchvision on CUDA 12.1 instead of 11.7.

I'll update them soon on new commit.

**Comment by Jianxff** [comment]
updated. you can try the latest commit.

**Comment by Mio-Atse** [comment]
I created a file to use on google colab. You can try similar errors commands on your own computer. Don't forget to replace the requirements.txt file. Also the last lines are created for the video test. You can delete it.

[Here](https://colab.research.google.com/drive/1LpYb6PnyPE2Tf3npA5-wtae2UGg3bTKu?usp=sharing)
